### ISSUE TITLE
plex-stats

### ISSUE THREAD

**Issue by unixjeff** [ryanleonard1/PlexMOTD#1]
Can't seem to get it to output the data from plex. first I tried just updating the config with api and no results. changed the url to 127.0.0.1 and $serverip still nothing. I changed the code in 08-plex-stats to just call the url directly and still no luck :( 

https://pastebin.com/CpbJtWxe

any suggestions?

**Comment by 40Cakes** [comment]
Hi there, looks like you haven't replaced apikey with your own Tautulli API key.

You can find it under Tautulli > Settings > Web Interface > API

**Comment by unixjeff** [comment]
Sorry I removed the key :)

**Comment by 40Cakes** [comment]
What output are you getting when you run the following?
`curl -s "http://127.0.0.1:8086/api/v2?apikey=apikey&cmd=get_activity"`

If you're using HTTPS, you may have to add `-k` to the `curl `command to skip the certificate check (I am not using HTTPS).

You don't need to add `echo "scale=2";` to the first command, all this does is is provides the Plex bandwidth to 2 decimal places.

**Comment by unixjeff** [comment]
Output looks good

https://privatebin.net/?d90903c229646ed5#YOO7IPFy+4dxaSWXNPVvYL+qHunRz2NEE5wbgCaL/zs=

**Comment by 40Cakes** [comment]
Bizarre, it worked fine for me using the output you provided... Maybe you could redirect the output of curl to a temp file and then run jq?

`ryan@plex:~$ cat tmp.txt | jq '.response.data.total_bandwidth'`
6812

**Comment by yeyeoke** [comment]
I'm having the exact same issue, with an identical output. I'm not sure if it has anything to do with the fact that I have base_url set to /tautulli.

**Comment by Logvin** [comment]
yeyeoke thats exactly what the issue is. I worked around it like this:
```

#!/bin/bash

source /etc/update-motd.d/config.conf
source /etc/update-motd.d/colors.txt
TAUTCONNECT="$TAUTIP/api/v2?apikey=$TAUTAPI&cmd=get_activity"

PLEXSTATS="$(curl -s "$TAUTCONNECT")"
echo -e " ${YEL}Tautulli Check......:${NC} Tautulli is running at $TAUTCONNECT"
echo -e " ${YEL}Plex Streams........:${NC} There are currently ${PUR}$(curl -s "$TAUTCONNECT" | tac | tac | jq '.response.data.strea$
echo -e " ${YEL}Plex Bandwidth......:${NC} Plex streams are using ${PUR}$(echo "scale=2; $(echo $PLEXSTATS | jq '.response.data.tota$
echo -e " ${YEL}                     ${NC} (${PUR}$(echo "scale=2; $(echo $PLEXSTATS | jq '.response.data.wan_bandwidth') / 1024" | $
```

I then modified my config.conf file:

`TAUTIP="http://localhost:8181/tautulli" # Tautulli IP/Hostname`

I don't even use the TAUTPORT, I just worked it all into the TAUTIP.

**Comment by yeyeoke** [comment]
@Logvin Thanks for the suggestion, sadly that didnt work either, is there anything I have to modify before editing my motd? I simply copied the scripts to /etc/update-motd.d.

**Comment by Logvin** [comment]
Did you update config.conf to match your URL and API key?

Trying getting out of the script alltogether and doing this...

`curl -s "http://127.0.0.1:8086/api/v2?apikey=apikey&cmd=get_activity"`

Obviously copy/paste your API key in there. Do this from your CLI and see if it returns anything.

**Comment by yeyeoke** [comment]
@Logvin Yeah thats already checked, I've also installed the dependencies you mentioned in your other issue. I noticed that while running "sudo run-parts /etc/update-motd.d/" I get the following; 

/etc/update-motd.d//08-plex-stats: line 11: unexpected EOF while looking for matching `)'
/etc/update-motd.d//08-plex-stats: line 12: syntax error: unexpected end of file
run-parts: /etc/update-motd.d//08-plex-stats exited with return code 2

**Comment by yeyeoke** [comment]
@Logvin nevermind, after installing the dependencies and figuring out the copy-paste of your config got cut off, I finally got it working as expected. Thank you! :+1:

**Comment by Logvin** [comment]
YAY! Glad to hear.

**Comment by unixjeff** [comment]
This was resolved by installing jq and bc

sudo apt install jq bc
