### ISSUE TITLE
JavaQuery is a dependancy

### ISSUE THREAD

**Issue by Logvin** [ryanleonard1/PlexMOTD#3]
Need to run this command to install JavaQuery or the Tautulli stats wont work.

`sudo apt install jq`

**Comment by Logvin** [comment]
So is BC...

`sudo apt-get install bc`

**Comment by Ackis** [comment]
https://github.com/Ackis/PlexMOTD/commit/259a6c84806d4770ab37261bb17bdd7f5eea180a

**Comment by 40Cakes** [comment]
Thanks, added a dependency check.
You will now receive a message if you don't have jq or bc installed.
