### ISSUE TITLE
[Feature Request] Sabnzb queue

### ISSUE THREAD

**Issue by unixjeff** [ryanleonard1/PlexMOTD#4]
I would love to have the current # of items in queue as one of the items displayed

**Comment by 40Cakes** [comment]
I'll see what I can do, shouldn't be too hard.

**Comment by 40Cakes** [comment]
Hi mate,

Can you give this a crack and let my know how it goes? https://github.com/ryanleonard1/PlexMOTD/commit/bc68d4027d5baf69b378a62313032ec32c72a991

Returns this information for me:
>  SABNZBD Queue.......: There are currently 1 slots in queue
>  SABNZBD Speed.......: Currently downloading at 1120.42 KB/s
>  Remaining...........: 4.86 MB

I'm don't really use Usenet at all, I hope the terminology I used is correct...
Also I am using a deprecated API call ([qstatus](https://sabnzbd.org/wiki/advanced/api#qstatus)) to retrieve the stats, it may be removed at any time without notice, I could not get '[queue](https://sabnzbd.org/wiki/advanced/api#queue)' to work.

**Comment by unixjeff** [comment]
Perfect! Thank you
https://i.imgur.com/sKkInbW.png
