### ISSUE TITLE
Modifying banner

### ISSUE THREAD

**Issue by yeyeoke** [ryanleonard1/PlexMOTD#5]
Your banner is awesome, so awesome I'd like to modify it to be used with my torrent-server but I can't for the life of me figure out how to create a similar banner with another text. I've googled but every motd tutorial uses normal characters that simply doesn't look nearly as good.

**Comment by 40Cakes** [comment]
Hi mate,

I converted the logo from image to ASCII art using [this tool](https://manytools.org/hacker-tools/convert-images-to-ascii-art/).

I then manually recolored the logo and did a find and replace on all the characters and replaced them with whitepace and █.
